# Generated by Django 6.1.1 on 2026-09-17 07:48

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('utilisateur', 'Utilisateur')], default='utilisateur', max_length=20, verbose_name='Rôle')),
                ('organisation', models.CharField(blank=True, max_length=150, verbose_name='Organisation')),
                ('fonction', models.CharField(blank=True, max_length=150, verbose_name='Fonction')),
                ('cree_le', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Créé le')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=200, verbose_name='Titre')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('maj_le', models.DateTimeField(auto_now=True, verbose_name='Mise à jour le')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
                'ordering': ['-maj_le'],
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200, verbose_name='Action')),
                ('detail', models.CharField(blank=True, max_length=400, verbose_name='Détail')),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journaux', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Entrée du journal',
                'verbose_name_plural': 'Journal',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('utilisateur', 'Utilisateur'), ('assistant', 'Assistant')], max_length=20, verbose_name='Rôle')),
                ('mode', models.CharField(choices=[('en_ligne', 'En ligne'), ('hors_ligne', 'Hors ligne')], default='en_ligne', max_length=20, verbose_name='Mode de réponse')),
                ('contenu', models.TextField(verbose_name='Contenu')),
                ('sources', models.JSONField(blank=True, default=list, verbose_name='Sources')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='conjoncture.conversation', verbose_name='Conversation')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['cree_le'],
            },
        ),
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=250, verbose_name='Titre')),
                ('type_rapport', models.CharField(choices=[('synthese', 'Synthèse conjoncturelle'), ('regional', 'Profil régional'), ('pays', 'Profil pays CEMAC'), ('statistique', 'Note statistique')], default='synthese', max_length=20, verbose_name='Type de rapport')),
                ('cible', models.CharField(blank=True, help_text='Région ou pays concerné, si applicable.', max_length=100, verbose_name='Cible')),
                ('periode', models.CharField(blank=True, help_text='Exemple : 2025 ou 2020-2025.', max_length=60, verbose_name='Période')),
                ('fichier', models.FileField(blank=True, upload_to='rapports/%Y/%m/', verbose_name='Fichier PDF')),
                ('donnees', models.JSONField(blank=True, default=dict, verbose_name='Données du rapport')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('genere_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports', to=settings.AUTH_USER_MODEL, verbose_name='Généré par')),
            ],
            options={
                'verbose_name': 'Rapport',
                'verbose_name_plural': 'Rapports',
                'ordering': ['-cree_le'],
            },
        ),
    ]
