# Generated by Django 6.1.1 on 2026-09-17 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conjoncture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SerieDonnees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=80, unique=True, verbose_name='Code')),
                ('libelle', models.CharField(max_length=200, verbose_name='Libellé')),
                ('unite', models.CharField(blank=True, max_length=30, verbose_name='Unité')),
                ('periodicite', models.CharField(choices=[('annuelle', 'Annuelle'), ('semestrielle', 'Semestrielle'), ('trimestrielle', 'Trimestrielle'), ('mensuelle', 'Mensuelle')], default='annuelle', max_length=20, verbose_name='Périodicité')),
                ('nature', models.CharField(choices=[('publique', 'Publique'), ('confidentielle', 'Confidentielle')], default='publique', max_length=20, verbose_name='Nature')),
                ('entite_type', models.CharField(blank=True, default='', help_text='Pays, région, ville, secteur… Laissez vide si sans objet.', max_length=20, verbose_name="Type d'entité")),
                ('source', models.CharField(blank=True, max_length=200, verbose_name='Source')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
            ],
            options={
                'verbose_name': 'Série de données',
                'verbose_name_plural': 'Séries de données',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='ImportDonnees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(blank=True, upload_to='imports/%Y/%m/', verbose_name='Fichier source')),
                ('nom_fichier', models.CharField(max_length=255, verbose_name='Nom du fichier')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('partiel', 'Partiellement importé'), ('rejete', 'Rejeté')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('lignes_lues', models.IntegerField(default=0, verbose_name='Lignes lues')),
                ('lignes_importees', models.IntegerField(default=0, verbose_name='Lignes importées')),
                ('lignes_rejetees', models.IntegerField(default=0, verbose_name='Lignes rejetées')),
                ('erreurs', models.JSONField(blank=True, default=list, verbose_name='Erreurs')),
                ('apercu', models.JSONField(blank=True, default=dict, verbose_name='Aperçu')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('importe_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imports', to=settings.AUTH_USER_MODEL, verbose_name='Importé par')),
                ('serie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imports', to='conjoncture.seriedonnees', verbose_name='Série cible')),
            ],
            options={
                'verbose_name': 'Import de données',
                'verbose_name_plural': 'Imports de données',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='PointDonnee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entite', models.CharField(blank=True, help_text='Pays, région ou ville concernée. Vide = ensemble.', max_length=120, verbose_name='Entité')),
                ('periode', models.CharField(help_text='2024 (annuel), 2024-T1 (trimestriel), 2024-03 (mensuel).', max_length=20, verbose_name='Période')),
                ('valeur', models.FloatField(verbose_name='Valeur')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='conjoncture.seriedonnees', verbose_name='Série')),
            ],
            options={
                'verbose_name': 'Point de donnée',
                'verbose_name_plural': 'Points de données',
                'ordering': ['serie', 'periode'],
                'unique_together': {('serie', 'entite', 'periode')},
            },
        ),
    ]
